theme: jekyll-theme-slate
github:
  repository_url: https://github.com/siloutil/siloutil
  is_project_page: true
  owner_name: Niklas Donocik
  owner_url: https://github.com/toxciq-math
  owner_mail: siloutil@donocik.name
title: siloutil
description:  You can't change physics, but you can change your visualization
