theme: jekyll-theme-slate
github:
  repository_url: https://github.com/siloutil/siloutil
title: siloutil
description:  A collection of command line tools and a python module to manipulate .silo files, mainly those created by A.I.K.E.F.
